image: maven:latest


test:
    script:
       mvn test -Dtest=consultaRestricoesCpf#verificarStatusCpfLimpo test
    script:
       mvn test -Dtest=consultaRestricoesCpf#verificarStatusCpfSujo test
    script:
       mvn test -Dtest=consultaRestricoesCpf#verificarMensagem test       mvn test -Dtest=consultaSimulacoesExistentes#verificarNumerosCpf test

    script:
       mvn test -Dtest=consultaSimulacoesExistentes#verificarNumerosCpf test
    script:
       mvn test -Dtest=consultaSimulacoesExistentes#validarValorZerado test
    script:
       mvn test -Dtest=consultaSimulacoesExistentes#validarRc test
    tags:
      - executeTests
       

   

    